server:
    port: 50059
    is_enabled_all_services: fill_is_is_enabled_all_services
    services:
        - services_enabled
    host: localhost
    log_level: WARNING
    jwt_secret_key: fill_secret_key
    # Default 24 hours
    jwt_expiration_time: fill_expiration_time
database:
    host: localhost
    port: 5432
    name: adempiere_database_value
    user: adempiere_user_value
    password: adempiere_pass_value
    type: PostgreSQL
