# This workflow will build a Java project with Gradle
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Add support to default build

name: Continuous Integration with Gradle

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths-ignore:
      - README.md
      - README.es.md

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - test/**
      - bugfix/**
      - feature/**
    paths-ignore:
      - README.md
      - README.es.md
      - docker/*

jobs:

  build-ci:
    name: Build ADempiere gRPC Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Java JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 11
          architecture: x64

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        env:
          GITHUB_DEPLOY_USER: ${{ github.actor }}
          GITHUB_DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          GITHUB_DEPLOY_REPOSITORY: ${{ secrets.DEPLOY_REPOSITORY }}
          GITHUB_SPDEV_USER: ${{ secrets.GH_SPDEV_USER }}
          GITHUB_SPDEV_TOKEN: ${{ secrets.GH_SPDEV_TOKEN }}
          # ORG_GRADLE_PROJECT_deployUsername: ${{ secrets.DEPLOY_USER }}
          # ORG_GRADLE_PROJECT_deployToken: ${{ secrets.DEPLOY_TOKEN }}
          # ORG_GRADLE_PROJECT_deployRepository: ${{ secrets.DEPLOY_REPOSITORY }}
        with:
          gradle-version: 8.0.2
          arguments: build

    #   - name: Upload descriptor file artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: adempiere-grpc-server.pb
    #       path: build/descriptors/adempiere-grpc-server.pb
    #       retention-days: 7
